[shell]
program = "/opt/homebrew/bin/fish"

[font] 
size = 13.5
normal = {family = "MonaspiceNe Nerd Font", style = "Regular"}
builtin_box_drawing = true

[window]
opacity = 0.9999
startup_mode = "Maximized"
[colors.primary]
background = '#15141b'
foreground = '#edecee'

[colors.cursor]
text = '#191d21'
cursor = '#E0E0E0'

[env]
TERM = 'xterm-256color'



# local bg = '#101113'
# -- '#0B0E14'
# local fg = '#F1F2F8'
#
# local red = '#FF4747'
# local redBright = '#FF6B6B'
# local greenBright = '#5CFFB6'
# local green = '#00F587'
# local yellow = '#D7F75B'
# local purple = '#7C53ED'
# local lightBlue = '#ABFFFF'
# local yellow2 = '#A4CF4A'
# local orange = '#F68A3E'

# Normal colors
[colors.normal]
black   = '#110f18'
red     = '#ff6767'
green   = '#61ffca'
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'

# Bright colors
[colors.bright]
black   = '#4d4d4d'
red     = '#ff6767'
green   = '#61ffca'
yellow  = '#ffca85'
blue    = '#a277ff'
magenta = '#a277ff'
cyan    = '#61ffca'
white   = '#edecee'

[colors.selection]
text       = 'CellForeground'
background = '#29263c'

