[shell]
program = "/opt/homebrew/bin/fish"

[font] 
size = 13.5
normal = {family = "MonaspiceNe Nerd Font", style = "Regular"}
builtin_box_drawing = true

[window]
opacity = 0.9999
startup_mode = "Maximized"

[colors.primary]
background = '#15181B'
foreground = '#E0E0E0'

[colors.cursor]
text = '#191d21'
cursor = '#E0E0E0'

[env]
TERM = 'xterm-256color'



# local bg = '#101113'
# -- '#0B0E14'
# local fg = '#F1F2F8'
#
# local red = '#FF4747'
# local redBright = '#FF6B6B'
# local greenBright = '#5CFFB6'
# local green = '#00F587'
# local yellow = '#D7F75B'
# local purple = '#7C53ED'
# local lightBlue = '#ABFFFF'
# local yellow2 = '#A4CF4A'
# local orange = '#F68A3E'

# Normal colors
[colors.normal]
black   = '#101113'
red     = '#FF4747'
green   = '#00F587'
yellow  = '#D7F75B'
blue    = '#ABFFFF'
magenta = '#7C53ED'
cyan    = '#B267E6'
white   = '#F1F2F8'

# Bright colors
[colors.bright]
black   = '#101113'
red     = '#E61F44'
green   = '#B7F0E5'
yellow  = '#A7C7ED'
blue    = '#A7C7ED'
magenta = '#EE808B'
cyan    = '#D7C9F0'
white   = '#E0E0E0'
