[shell]
program = "/opt/homebrew/bin/fish"

[font] 
size = 13.5
normal = {family = "MonaspiceNe Nerd Font", style = "Regular"}
builtin_box_drawing = true

[window]
opacity = 0.9999
startup_mode = "Maximized"

[colors.primary]
background = '#15181B'
foreground = '#E0E0E0'

[colors.cursor]
text = '#191d21'
cursor = '#E0E0E0'

# Normal colors
[colors.normal]
black   = '#34393E'
red     = '#E61F44'
green   = '#5BD1B9'
yellow  = '#53A1FA'
blue    = '#53A1FA'
magenta = '#F4457D'
cyan    = '#B267E6'
white   = '#E0E0E0'

# Bright colors
[colors.bright]
black   = '#45505b'
red     = '#E61F44'
green   = '#B7F0E5'
yellow  = '#A7C7ED'
blue    = '#A7C7ED'
magenta = '#EE808B'
cyan    = '#D7C9F0'
white   = '#E0E0E0'
