"$schema" = 'https://starship.rs/config-schema.json';

 format= """
"""

palette = 'onehunter'

[palettes.onehunter]
black_bright   = '#45505B'
red_bright     = '#F3447D'
green_bright   = '#B8EFE5'
yellow_bright  = '#45505B'
blue_bright    = '#6282B9'
magenta_bright = '#ED808B'
cyan_bright    = '#D7C9F0'
white_bright   = '#E0E0E0'
black   = '#191D21'
red     = '#F44748'
green   = '#5BD0B9'
yellow  = '#F9C35A'
blue    = '#43AAF9'
magenta = '#B480D6'
cyan    = '#70C6E6'
white   = '#E0E0E0'
