[shell]
program = "/opt/homebrew/bin/fish"

[font] 
size = 13.5
normal = {family = "MonaspiceNe Nerd Font", style = "Regular"}
builtin_box_drawing = true

[window]
opacity = 0.9999
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"
[colors.primary]
background = '#0F111A'
foreground = '#A6ACCD'

[colors.cursor]
text = '#191d21'
cursor = '#E0E0E0'

[env]
TERM = 'xterm-256color'

[colors.bright]
black	= '#0F1119'
red		= '#DC6068'
green 	= '#91B859'
yellow  = '#F6A434'
blue    = '#6182B8'
magenta = '#7C4DFF'
cyan    = '#39ADB5'
white   = '#EFFFFF'

[colors.normal]
black   = '#0F1119'
red     = '#E53935'
green   = '#ABCF76'
yellow  = '#E6B455'
blue    = '#6E98EB'
magenta = '#B480D6'
cyan    = '#71C6E7'
white   = '#EFFFFF'

[colors.selection]
text       = 'CellForeground'
background = '#29263c'

